# Users Requests

### Get user by ID

GET http://localhost:3000/auth/3

### Find all users with a given email

GET http://localhost:3000/auth?email=andreas@test.de

### Signup new user

POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "test1@test.de",
  "password": "asdf",
  "test": "abc"
}

### Signin existing user

POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "test@test.de",
  "password": "asdf"
}

### Update a user by ID

PATCH http://localhost:3000/auth/2
content-type: application/json

{
  "email": "andreas@test2.de"
}

### Delete a user by ID

DELETE http://localhost:3000/auth/2

### Who am I (get current user)

GET http://localhost:3000/auth/whoami

### Signout current user

POST http://localhost:3000/auth/signout
